version: "4.1"

services:
  postgres:
    image: postgres:15-alpine
    container_name: demo-postgres
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: demo_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  
  app-server:
    build:
      context: .
      dockerfile: demo-app.dockerfile
    command: ["./server", "server"]
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      DATABASE_URL: postgres://demo_user:demo_pass@postgres:5432/demo_db?sslmode=disable
      GATEWAY_GRPC_ADDR: app-server:9090
      Pubsub_Endpoint: dns:///host.docker.internal:8085
      Pubsub_Topic: transactions
      Redis_Addr: redis:6379


  app-consumer-pubsub:
    build:
      context: .
      dockerfile: demo-app.dockerfile
    command: ["./server", "pubsub-consumer"]
    environment:
      PROJECT_ID: demo-project
      Pubsub_Endpoint: dns:///host.docker.internal:8085
      Pubsub_Subcription: sub-transactions
      Pubsub_Topic: transactions

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"] 
    volumes:
      - redis-data:/data
      
      
      
volumes:
  redis-data:


