apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-consumer
  template:
    metadata:
      labels:
        app: app-consumer
    spec:
      containers:
        - name: app-consumer
          image: docker.io/library/app-server:latest
          imagePullPolicy: Never
          command: ["./server", "consumer"]
          env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: PROJECT_ID
              value: demo-project
            - name: PubSub_Endpoint
              value: host.docker.internal:8085
            - name: Pubsub_Topic
              value: transactions
