apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.6
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
      volumes:
        - name: kafka-data
          emptyDir: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-create-topic
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-topic
          image: bitnami/kafka:3.6
          command:
            - sh
            - -c
            - |
              echo "Waiting for Kafka to be ready..."
              sleep 10
              /opt/bitnami/kafka/bin/kafka-topics.sh --create \
                --topic transactions \
                --bootstrap-server kafka:9092 \
                --replication-factor 1 \
                --partitions 1 || true
