apiVersion: v1
kind: Pod
metadata:
  name: kafka-debug
  labels:
    app: kafka
spec:
  restartPolicy: Never   # 👈 chỉ chạy một lần
  containers:
    - name: kafka
      image: confluentinc/cp-kafka:7.5.0
      ports:
        - containerPort: 9092
      env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka.default.svc.cluster.local:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
      volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
  volumes:
    - name: kafka-data
      emptyDir: {}
